name: Publish portfolio to Hostinger dev channel
on:
  push:
    branches:
      - dev
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action-Dev
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2.3.2

    - name: Install Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 14.x

    - name: Install NPM packages
      working-directory: ./frontend
      run: npm ci

    - name: Build project
      working-directory: ./frontend
      run: npm run build

    - name: FTP-Deploy-Action-Dev
      uses: SamKirkland/FTP-Deploy-Action@4.0.0
      with:
        server: ${{ secrets.FTP_SERVER }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        local-dir: ./frontend/build/
        server-dir: public_html/dev/